# Generated by Django 3.2.5 on 2021-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='PoNumber',
            field=models.IntegerField(null=True, verbose_name='P.O Number'),
        ),
    ]
