# Generated by Django 3.2.5 on 2021-07-17 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_invoice_ponumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_backup', models.CharField(max_length=500, null=True)),
                ('email_backup', models.EmailField(max_length=254, null=True)),
                ('phone_backup', models.PositiveIntegerField(null=True)),
                ('address_backup', models.CharField(max_length=500, null=True)),
                ('PoNumber', models.IntegerField(null=True, verbose_name='P.O Number')),
                ('PaymentType', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit')], max_length=50, null=True, verbose_name='Payment Type')),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('Total', models.FloatField(default=0.0, null=True)),
                ('discount', models.FloatField(default=0.0, null=True, verbose_name='Discount')),
                ('currency', models.CharField(choices=[('HTG', 'HTG')], default='HTG', max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer')),
            ],
            options={
                'ordering': ('Date',),
            },
        ),
        migrations.CreateModel(
            name='Salesorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_backup', models.CharField(max_length=500, null=True)),
                ('email_backup', models.EmailField(max_length=254, null=True)),
                ('phone_backup', models.PositiveIntegerField(null=True)),
                ('address_backup', models.CharField(max_length=500, null=True)),
                ('PoNumber', models.IntegerField(null=True, verbose_name='P.O Number')),
                ('PaymentType', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit')], max_length=50, null=True, verbose_name='Payment Type')),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('Total', models.FloatField(default=0.0, null=True)),
                ('discount', models.FloatField(default=0.0, null=True, verbose_name='Discount')),
                ('currency', models.CharField(choices=[('HTG', 'HTG')], default='HTG', max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer')),
            ],
            options={
                'ordering': ('Date',),
            },
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='dueQuantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Due Qtty'),
        ),
        migrations.CreateModel(
            name='SalesorderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=500, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('dueQuantity', models.PositiveIntegerField(null=True, verbose_name='Due Qtty')),
                ('price', models.FloatField(null=True)),
                ('Total', models.FloatField(null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product')),
                ('Salesorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('Delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.delivery')),
                ('Invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.invoice')),
                ('Salesorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=500, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('dueQuantity', models.PositiveIntegerField(null=True, verbose_name='Due Qtty')),
                ('price', models.FloatField(null=True)),
                ('Total', models.FloatField(null=True)),
                ('Delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.delivery')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product')),
            ],
        ),
    ]
