# Generated by Django 3.2.5 on 2021-07-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210717_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='quantity',
            new_name='Amount',
        ),
    ]
