# Generated by Django 3.2.5 on 2021-07-17 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_quantity_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField(null=True)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('Delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField(null=True)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('Invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesorderDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField(null=True)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('Salesorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesorder')),
            ],
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
