# Generated by Django 3.2.5 on 2021-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210717_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedeposit',
            name='Amount',
            field=models.FloatField(null=True),
        ),
    ]
