# Generated by Django 3.2.5 on 2021-07-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_invoicedeposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Balance',
            field=models.FloatField(null=True),
        ),
    ]
