# Generated by Django 3.2.5 on 2021-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_invoice_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Funds',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
