# Generated by Django 3.2.5 on 2021-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_invoiceproduct_duequantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedeposit',
            name='Type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=50, null=True, verbose_name='Payment Type'),
        ),
    ]
