# Generated by Django 3.2.5 on 2021-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_invoicedeposit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Type',
            field=models.CharField(choices=[('Invoice', 'Invoice'), ('Sales Order', 'Sales Order'), ('Delivery', 'Delivery')], max_length=50, null=True, verbose_name='Invoice Type'),
        ),
    ]
