# Generated by Django 3.2.5 on 2021-07-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='Total',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
